version: '3.6'
services:
  bald-wars-database:
    container_name: bald-wars-database
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
  bald-wars-api:
    container_name: bald-wars-api
    image: node:16.6.1-alpine3.13
    depends_on:
      - bald-wars-database
    ports:
      - '${API_PORT}:${API_PORT}'
    volumes:
      - './backend:/app'
    env_file:
      - .env
    working_dir: /app
    entrypoint: sh -c "npm i && npm start"
  bald-wars-sandbox:
    container_name: bald-wars-sandbox
    image: node:16.6.1-alpine3.13
    ports:
      - '${SANDBOX_PORT}:${SANDBOX_PORT}'
    volumes:
      - './sandbox:/app/sandbox'
      - './character-lib:/app/character-lib'
    env_file:
      - .env
    working_dir: /app/sandbox
    entrypoint: sh -c "npm i && npm start"
